service:
  annotations:
    {
      "oci.oraclecloud.com/load-balancer-type":"lb",
      "service.beta.kubernetes.io/oci-load-balancer-shape":"flexible",
      "service.beta.kubernetes.io/oci-load-balancer-shape-flex-min":"10",
      "service.beta.kubernetes.io/oci-load-balancer-shape-flex-max":"10",
      "oci.oraclecloud.com/oci-network-security-groups":"${PUB_NSG_ID}",
      "oci.oraclecloud.com/security-rule-management-mode":"None"
    }