apiVersion: v1
kind: Secret
metadata:
  name: s3creds
  annotations:
    serving.kserve.io/s3-endpoint: "{object-storage-namespace}.compat.objectstorage.{region}.oraclecloud.com"
    serving.kserve.io/s3-region: "{region}"
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {s3_access_key_id}
  AWS_SECRET_ACCESS_KEY: {s3_access_key}
