tracking:
  service:
    annotations:
      "oci.oraclecloud.com/load-balancer-type":"lb",
      "service.beta.kubernetes.io/oci-load-balancer-shape":"flexible",
      "service.beta.kubernetes.io/oci-load-balancer-shape-flex-min":"10",
      "service.beta.kubernetes.io/oci-load-balancer-shape-flex-max":"10",
      "oci.oraclecloud.com/oci-network-security-groups":"{pub_lb_nsg_id}",
      "oci.oraclecloud.com/security-rule-management-mode":"None"

run:
  enabled: false

minio:
  enabled: false

externalS3:
  host: {object-storage-namespace}.compat.objectstorage.{region}.oraclecloud.com
  bucket: mlflow
  accessKeyID: {key_id}
  accessKeySecret: {key_secret}